In [1]:
import numpy as np

In [5]:
u=np.array([2,4,6,8])
v=np.array([1,3,5,7])

v+u

array([ 3,  7, 11, 15])

In [40]:
x = np.round(np.linspace(2,10,4),0)
y = np.round(np.linspace(1,10,4),0)

# np.dot(x,y)

x.dot(y)

171.0

In [130]:
U=np.array([[2,4,5,6],[1,2,1,2],[3,1,2,1]])
V=np.array([[1,1,2],[0,0.5,1],[0,2,1],[2,1,0]])

# U.dot(V)



def matrix_X_matrix(u,v):
    assert u.shape[0] == v.shape[1]
    num_rows= u.shape[0]
    num_cols= v.shape[1]
    result = np.zeros((num_rows,num_cols))
    for i in range(num_cols):
        uc = v[:,i]
        uci= u.dot(uc)
        result[:,i]=uci
    return result
U.shape
V.shape
matrix_X_matrix(U,V)




array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [82]:
tt=np.array([[2,4,5,6],[1,2,1,2],[3,1,2,1]])
tt[0,:]
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [86]:
x=np.linspace(2,6,4)
y=np.array([1,0,0,2])

x.dot(y)

14.0

In [157]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])
X=np.array([[2,4,5,6],
            [1,2,1,2]])


In [138]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [166]:
Vs=V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [170]:
Vsi=np.linalg.inv(Vs)
Vsi

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [172]:
Vsi.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])