In [2]:
import numpy as np

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.full(10,1.0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [17]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [25]:
np.linspace(0, 1000, 1001)

array([   0.,    1.,    2., ...,  998.,  999., 1000.])

In [6]:
np.full((2,1),10)

array([[10],
       [10]])